<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/Data-Analatics/blob/main/DATASET_CREATION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

data = {
   "emp_id": [101, 102, 103, 104, 105],
   "name": ["Asha", "Ravi", "Kiran", "Neha", "Arjun"],
   "department": ["IT", "HR", "IT", "Finance", "HR"],
   "salary": [60000, 45000, 70000, 50000, 48000],
   "experience": [3, 2, 5, 4, 1]
}
df = pd.DataFrame(data)

In [2]:
df.loc[df["department"] == "IT", ["name", "salary"]]

    name  salary
0   Asha   60000
2  Kiran   70000

task 1.2

In [3]:
df.iloc[:3, :2]

   emp_id   name
0     101   Asha
1     102   Ravi
2     103  Kiran

task 1.3

In [4]:
df.iloc[0]

emp_id          101
name           Asha
department       IT
salary        60000
experience        3
Name: 0, dtype: object

In [5]:
df.loc[0]

emp_id          101
name           Asha
department       IT
salary        60000
experience        3
Name: 0, dtype: object

In [10]:
df = df.set_index("emp_id")

KeyError: "None of ['emp_id'] are in the columns"

renaming columns

task 2.1

In [12]:
df = df.rename(columns={
    "emp_id": "employee_id",
    "name": "employee_name"
})

df

       employee_name department  salary  experience
emp_id
101             Asha         IT   60000           3
102             Ravi         HR   45000           2
103            Kiran         IT   70000           5
104             Neha    Finance   50000           4
105            Arjun         HR   48000           1

 task 2.2 convert to names to upper

In [13]:
df.columns = df.columns.str.upper()

df

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
101             Asha         IT   60000           3
102             Ravi         HR   45000           2
103            Kiran         IT   70000           5
104             Neha    Finance   50000           4
105            Arjun         HR   48000           1

 task 3.1 removing / deleting rows&columns

In [24]:
df['bonus']=0

In [25]:
df = df.drop("bonus", axis=1)

In [26]:
df = df.drop("bonus", axis=1,errors="ignore")

In [27]:
df['bonus']=0
df=df.drop('bonus',axis=1)

delete employees with experience < 2

In [31]:
df.columns

Index(['EMPLOYEE_NAME', 'DEPARTMENT', 'SALARY', 'EXPERIENCE'], dtype='object')

In [33]:
df.columns=df.columns.str.upper()

In [35]:
df = df[df["EXPERIENCE"] >= 2]

df

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
101             Asha         IT   60000           3
102             Ravi         HR   45000           2
103            Kiran         IT   70000           5
104             Neha    Finance   50000           4

In [37]:
df = df[df["EMPLOYEE_NAME"] != "Neha"]

df

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
101             Asha         IT   60000           3
102             Ravi         HR   45000           2
103            Kiran         IT   70000           5

BOOLEAN INDEX

TASK 4.1

In [39]:
df[(df["DEPARTMENT"] == "HR") & (df["SALARY"] > 46000)]

Empty DataFrame
Columns: [EMPLOYEE_NAME, DEPARTMENT, SALARY, EXPERIENCE]
Index: []

TASK 4.2

In [40]:
df[(df["DEPARTMENT"] == "IT") | (df["EXPERIENCE"] >= 5)]

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
101             Asha         IT   60000           3
103            Kiran         IT   70000           5

AND,OR,NOT CONDITIONS
TASK 5.1 not

In [42]:
df[df["DEPARTMENT"] != "HR"]

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
101             Asha         IT   60000           3
103            Kiran         IT   70000           5

In [43]:
df[~(df["SALARY"] > 60000)]

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
101             Asha         IT   60000           3
102             Ravi         HR   45000           2

isin() and NOT IN
Task 6.1 — Department is IT or Finance

In [44]:
df[df["DEPARTMENT"].isin(["IT", "FINANCE"])]

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
101             Asha         IT   60000           3
103            Kiran         IT   70000           5

ask 6.2 — Names NOT in Asha and Arjun

In [51]:
df[~df["EMPLOYEE_NAME"].isin(["Asha", "Arjun"])]

       EMPLOYEE_NAME DEPARTMENT  SALARY  EXPERIENCE
emp_id
102             Ravi         HR   45000           2
103            Kiran         IT   70000           5

In [50]:
df.columns

Index(['EMPLOYEE_NAME', 'DEPARTMENT', 'SALARY', 'EXPERIENCE'], dtype='object')

tolist() and to_numpy()
Task 7.1 — Salary as Python list

In [53]:
salary_list = df["SALARY"].tolist()

print(salary_list)

[60000, 45000, 70000]

Task 7.2 — Entire DataFrame as NumPy array

In [54]:
array = df.to_numpy()

print(array)

[['Asha' 'IT' 60000 3]
 ['Ravi' 'HR' 45000 2]
 ['Kiran' 'IT' 70000 5]]

. set_index, reset_index, sort_index
Task 8.1 — Set employee_id as index

In [56]:
df = df.set_index("EMPLOYEE_NAME")

df

              DEPARTMENT  SALARY  EXPERIENCE
EMPLOYEE_NAME
Asha                  IT   60000           3
Ravi                  HR   45000           2
Kiran                 IT   70000           5

Task 8.2 — Sort by index

In [57]:
df = df.sort_index()

df

              DEPARTMENT  SALARY  EXPERIENCE
EMPLOYEE_NAME
Asha                  IT   60000           3
Kiran                 IT   70000           5
Ravi                  HR   45000           2

Task 8.3 — Reset index and drop old index

In [58]:
df = df.reset_index(drop=True)

df

  DEPARTMENT  SALARY  EXPERIENCE
0         IT   60000           3
1         IT   70000           5
2         HR   45000           2

astype()
Task 9.1
Convert salary to float:

In [60]:
df["SALARY"] = df["SALARY"].astype(float)

In [61]:
print(df.dtypes)

DEPARTMENT     object
SALARY        float64
EXPERIENCE      int64
dtype: object

10. sort_values()
Task 10.1 — Salary descending

In [62]:
df.sort_values(by="SALARY", ascending=False)

  DEPARTMENT   SALARY  EXPERIENCE
1         IT  70000.0           5
0         IT  60000.0           3
2         HR  45000.0           2

Task 10.2 — Department ascending + salary descending

In [63]:
df.sort_values(
    by=["DEPARTMENT", "SALARY"],
    ascending=[True, False]
)

  DEPARTMENT   SALARY  EXPERIENCE
2         HR  45000.0           2
1         IT  70000.0           5
0         IT  60000.0           3

11. drop()
Task 11.1 — Drop experience

In [64]:
df = df.drop("EXPERIENCE", axis=1)

df

  DEPARTMENT   SALARY
0         IT  60000.0
1         IT  70000.0
2         HR  45000.0

Task 11.2 — Drop rows where salary < 50000 using index-based logic
First find the indexes:

In [66]:
index_to_drop = df.index[df["SALARY"] < 50000]

print(index_to_drop)

Index([2], dtype='int64')