<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/Data-Analatics/blob/main/pandas_task_csv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('/content/sales_data_uncleaned.csv')
data

,OrderID,Date,CustomerName,Product,Category,Quantity,Price,Total,City
0,1001,05-01-2024,John Doe,Laptop,Electronics,1.0,800,NaN,New York
1,1002,06-01-2024,Jane Smith,Mobile,Electronics,2.0,500,1000.0,los angeles
2,1003,07-01-2024,NaN,Shoes,Fashion,3.0,50,150.0,Chicago
3,1004,07-01-2024,Emily Davis,T-shirt,Fashion,2.0,25,50.0,Boston
4,1005,08-01-2024,Michael Brown,Headphones,Electronics,1.0,100,100.0,new york
5,1006,08-01-2024,Chris Green,Laptop,Electronics,NaN,800,NaN,Los Angeles
6,1007,09-01-2024,Sarah Lee,Shoes,Fashion,1.0,55,55.0,Chicago
7,1008,10-01-2024,David Wilson,Laptop,Electronics,1.0,850,850.0,LOS ANGELES
8,1009,10-01-2024,Linda Taylor,T-shirt,Fashion,2.0,25,NaN,Boston
9,1010,11-01-2024,John Doe,NaN,Electronics,1.0,200,200.0,New York

In [3]:
(2) #loan dataset
data=pd.read_csv('/content/sales_data_uncleaned.csv')
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [11]:
(3) #first 5 rows
data.head()

,OrderID,Date,CustomerName,Product,Category,Quantity,Price,Total,City
0,1001,05-01-2024,John Doe,Laptop,Electronics,1.0,800,NaN,New York
1,1002,06-01-2024,Jane Smith,Mobile,Electronics,2.0,500,1000.0,los angeles
2,1003,07-01-2024,NaN,Shoes,Fashion,3.0,50,150.0,Chicago
3,1004,07-01-2024,Emily Davis,T-shirt,Fashion,2.0,25,50.0,Boston
4,1005,08-01-2024,Michael Brown,Headphones,Electronics,1.0,100,100.0,new york

In [12]:
(4) #specific columns
data[["CustomerName","Product","Total"]]

    CustomerName     Product   Total
0       John Doe      Laptop     NaN
1     Jane Smith      Mobile  1000.0
2            NaN       Shoes   150.0
3    Emily Davis     T-shirt    50.0
4  Michael Brown  Headphones   100.0
5    Chris Green      Laptop     NaN
6      Sarah Lee       Shoes    55.0
7   David Wilson      Laptop   850.0
8   Linda Taylor     T-shirt     NaN
9       John Doe         NaN   200.0

In [14]:
(5) #display missing values as "Missing"
data=pd.read_csv('/content/sales_data_uncleaned.csv').fillna("Missing")

Basic Inspection

In [17]:
(6)
data.head(7) #first 7 rows

,OrderID,Date,CustomerName,Product,Category,Quantity,Price,Total,City
0,1001,05-01-2024,John Doe,Laptop,Electronics,1.0,800,Missing,New York
1,1002,06-01-2024,Jane Smith,Mobile,Electronics,2.0,500,1000.0,los angeles
2,1003,07-01-2024,Missing,Shoes,Fashion,3.0,50,150.0,Chicago
3,1004,07-01-2024,Emily Davis,T-shirt,Fashion,2.0,25,50.0,Boston
4,1005,08-01-2024,Michael Brown,Headphones,Electronics,1.0,100,100.0,new york
5,1006,08-01-2024,Chris Green,Laptop,Electronics,Missing,800,Missing,Los Angeles
6,1007,09-01-2024,Sarah Lee,Shoes,Fashion,1.0,55,55.0,Chicago

In [18]:
(7) #last 3 rows
data.tail(3)

,OrderID,Date,CustomerName,Product,Category,Quantity,Price,Total,City
7,1008,10-01-2024,David Wilson,Laptop,Electronics,1.0,850,850.0,LOS ANGELES
8,1009,10-01-2024,Linda Taylor,T-shirt,Fashion,2.0,25,Missing,Boston
9,1010,11-01-2024,John Doe,Missing,Electronics,1.0,200,200.0,New York

In [19]:
(8) #number of rows and columns
data.shape

(10, 9)

In [20]:
(9) #column names
data.columns.tolist()

['OrderID',
 'Date',
 'CustomerName',
 'Product',
 'Category',
 'Quantity',
 'Price',
 'Total',
 'City']

In [21]:
(10) #data types
data.dtypes

OrderID          int64
Date            object
CustomerName    object
Product         object
Category        object
Quantity        object
Price            int64
Total           object
City            object
dtype: object

SUMMARY & METADATA

In [22]:
(11) #duplicate orderid
data.index.duplicated().any()

np.False_

In [23]:
(12) #information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       10 non-null     int64
 1   Date          10 non-null     object
 2   CustomerName  10 non-null     object
 3   Product       10 non-null     object
 4   Category      10 non-null     object
 5   Quantity      10 non-null     object
 6   Price         10 non-null     int64
 7   Total         10 non-null     object
 8   City          10 non-null     object
dtypes: int64(2), object(7)
memory usage: 852.0+ bytes

In [24]:
(13) #numerical summary
data.describe()

          OrderID      Price
count    10.00000   10.00000
mean   1005.50000  340.50000
std       3.02765  357.44036
min    1001.00000   25.00000
25%    1003.25000   51.25000
50%    1005.50000  150.00000
75%    1007.75000  725.00000
max    1010.00000  850.00000

In [26]:
(14) #categorical summary
data.describe(include="object")

,Date,CustomerName,Product,Category,Quantity,Total,City
count,10,10,10,10,10.0,10,10
unique,7,9,6,2,4.0,8,7
top,07-01-2024,John Doe,Laptop,Electronics,1.0,Missing,New York
freq,2,2,3,6,5.0,3,2

In [28]:
(15) #max and min price
print('Maximum:',data['Price'].max())
print('Minimum:',data['Price'].min())

Maximum: 850
Minimum: 25

Exploration

In [29]:
(16) #number of unique customers
data["CustomerName"].nunique()

9

In [30]:
(17) #unique categories
data["Category"].unique()

array(['Electronics', 'Fashion'], dtype=object)

In [31]:
(18) #product frequnecy
data['Product'].value_counts()

Product
Laptop        3
Shoes         2
T-shirt       2
Mobile        1
Headphones    1
Missing       1
Name: count, dtype: int64

In [32]:
(19) #city frequency
data['City'].value_counts()

City
New York       2
Chicago        2
Boston         2
los angeles    1
new york       1
Los Angeles    1
LOS ANGELES    1
Name: count, dtype: int64

In [33]:
(20) #null values
data.isnull().sum()

OrderID         0
Date            0
CustomerName    0
Product         0
Category        0
Quantity        0
Price           0
Total           0
City            0
dtype: int64