<a href="https://colab.research.google.com/github/addulamalerupareddy-gif/Data-Analatics/blob/main/Probability_CaseStudy_(3)_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_excel('/content/weather (2).xlsx')
df

    Day   Outlook Temperature Humidity    Wind Play
0     1     Sunny         Hot     High    Weak   No
1     2     Sunny         Hot     High  Strong   No
2     3  Overcast         Hot     High    Weak  Yes
3     4      Rain        Mild     High    Weak  Yes
4     5      Rain        Cool   Normal    Weak  Yes
5     6      Rain        Cool   Normal  Strong   No
6     7  Overcast        Cool   Normal  Strong  Yes
7     8     Sunny        Mild     High    Weak   No
8     9     Sunny        Cool   Normal    Weak  Yes
9    10      Rain        Mild   Normal    Weak  Yes
10   11     Sunny        Mild   Normal  Strong  Yes
11   12  Overcast        Mild     High  Strong  Yes
12   13  Overcast         Hot   Normal    Weak  Yes
13   14      Rain        Mild     High  Strong   No

In [7]:
df

    Day   Outlook Temperature Humidity    Wind Play
0     1     Sunny         Hot     High    Weak   No
1     2     Sunny         Hot     High  Strong   No
2     3  Overcast         Hot     High    Weak  Yes
3     4      Rain        Mild     High    Weak  Yes
4     5      Rain        Cool   Normal    Weak  Yes
5     6      Rain        Cool   Normal  Strong   No
6     7  Overcast        Cool   Normal  Strong  Yes
7     8     Sunny        Mild     High    Weak   No
8     9     Sunny        Cool   Normal    Weak  Yes
9    10      Rain        Mild   Normal    Weak  Yes
10   11     Sunny        Mild   Normal  Strong  Yes
11   12  Overcast        Mild     High  Strong  Yes
12   13  Overcast         Hot   Normal    Weak  Yes
13   14      Rain        Mild     High  Strong   No

In [8]:
df.head(2)

   Day Outlook Temperature Humidity    Wind Play
0    1   Sunny         Hot     High    Weak   No
1    2   Sunny         Hot     High  Strong   No

In [21]:
for i in df:
    print("*",i,"*")
    print(df[i].unique())

* Day *
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
* Outlook *
['Sunny' 'Overcast' 'Rain']
* Temperature *
['Hot' 'Mild' 'Cool']
* Humidity *
['High' 'Normal']
* Wind *
['Weak' 'Strong']
* Play *
['No' 'Yes']

# Marginal Probabilities(individual column)

### what is the probability of getting rain tommorow

In [13]:
df['Outlook'].value_counts(normalize=True)

Outlook
Sunny       0.357143
Rain        0.357143
Overcast    0.285714
Name: proportion, dtype: float64

### What is the probability of playing cricket tommorow?

In [16]:
df['Play'].value_counts(normalize=True).loc['Yes']

np.float64(0.6428571428571429)

### What is the Probability that temperature is not cool tommorow?

In [19]:
sum(df['Temperature']=='Cool')/len(df) #cool

0.2857142857142857

In [20]:
1-sum(df['Temperature']=='Cool')/len(df) #notcool

0.7142857142857143

### Joint Probabilites ( and | or) - Multiple Columns

### what is the probability of playing cricket and temparature is hot?

In [25]:
pd.crosstab(index=df['Play'],columns=df['Temperature'])

Temperature  Cool  Hot  Mild
Play
No              1    2     2
Yes             3    2     4

In [26]:
pd.crosstab(index=df['Play'],columns=df['Temperature'],normalize=True)

Temperature      Cool       Hot      Mild
Play
No           0.071429  0.142857  0.142857
Yes          0.214286  0.142857  0.285714

In [27]:
pd.crosstab(index=df['Play'],columns=df['Temperature'],normalize=True).loc['Yes']['Hot']

np.float64(0.14285714285714285)

### what is the probability of humidity is normal and temerature is cool?

In [28]:
pd.crosstab(index=df['Humidity'],columns=df['Temperature'])

Temperature  Cool  Hot  Mild
Humidity
High            0    3     4
Normal          4    1     2

In [29]:
pd.crosstab(index=df['Humidity'],columns=df['Temperature'],normalize=True)

Temperature      Cool       Hot      Mild
Humidity
High         0.000000  0.214286  0.285714
Normal       0.285714  0.071429  0.142857

In [34]:
pd.crosstab(index=df['Humidity'],columns=df['Temperature'],normalize=True).loc['Normal']['Cool']

np.float64(0.2857142857142857)

## Conditional Probability -- one is happend , what is the chance of other event

## what is probability of playing cricket if it is raining

In [45]:
pd.crosstab(index=df['Play'],columns=df['Outlook'],normalize='columns')

Outlook  Overcast  Rain  Sunny
Play
No            0.0   0.4    0.6
Yes           1.0   0.6    0.4

In [46]:
pd.crosstab(index=df['Play'],columns=df['Outlook'],normalize='columns').loc['Yes']['Rain']

np.float64(0.6)

## what is the probability of not playing cricket when humidity is high ?

In [35]:
pd.crosstab(index=df['Humidity'],columns=df['Temperature'],normalize='index')

Temperature      Cool       Hot      Mild
Humidity
High         0.000000  0.428571  0.571429
Normal       0.571429  0.142857  0.285714

In [41]:
pd.crosstab(index=df['Humidity'],columns=df['Temperature'],normalize='index')

Temperature      Cool       Hot      Mild
Humidity
High         0.000000  0.428571  0.571429
Normal       0.571429  0.142857  0.285714